# This is a basic workflow to help you get started with Actions

name: Build Gl-inet OpenWrt IPKs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  DOWNLOAD_SH: download.sh

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Initialization environment
        run: |
            sudo apt update && sudo apt upgrade -y
            sudo apt install asciidoc bash bc binutils bzip2 fastjar flex gawk gcc genisoimage gettext git intltool jikespg libgtk2.0-dev libncurses5-dev libssl1.0-dev make mercurial patch perl-modules python2.7-dev rsync ruby sdcc subversion unzip util-linux wget xsltproc zlib1g-dev zlib1g-dev -y

      # Runs a set of commands using the runners shell
      - name: download sdk
        working-directory: /
        run: |
          $GITHUB_WORKSPACE/$DOWNLOAD_SH ath79-1907
          cd sdk/1907/ath79/
          ./scripts/feeds update -f
          
      # Runs a set of commands using the runners shell
      - name: download package
        run: |
          cd  /sdk/1907/ath79/package
          git clone https://github.com/kenzok8/small-package.git
          
      # Runs a set of commands using the runners shell
      - name: build package
        run: |
          cd ..
          make package/small-package/luci-app-ssr-plus/compile V=s
          
          
          
